### ISSUE TITLE
Direct Linking to Orders

### ISSUE THREAD

**Issue by FrelliBB** [camilleriluke/ejja-ha-nieklu#31]
Currently when there are multiple orders open the main page loads with the first order created. For example; Optal created an order for Badass Burgers, and Capabilities opened an order for Mamma Mia. 

The page loads with the Optal order displayed and in order to view the Capabilities order the tab has to be clicked. There is no way to get a direct link to the capabilities order so it will be seen on page load.

**Comment by camilleriluke** [comment]
:+1:

**Comment by camilleriluke** [comment]
:+1:

**Comment by camilleriluke** [comment]
Btw feel free to submit a PR :)

**Comment by KPull** [comment]
Already implemented in https://github.com/camilleriluke/ejja-ha-nieklu/pull/29.

**Comment by camilleriluke** [comment]
Closing :)
