### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by FrelliBB** [camilleriluke/ejja-ha-nieklu#33]
It would be useful to be able to sort items in an order by item name. 

For example when phoning to order the meal instead of having to look through a large list for how many 'Chicken Burgers' there are, they would all be next to each other.

**Comment by camilleriluke** [comment]
Grouping is coming up soon once #29 is merged.

Closing for now.

**Comment by KPull** [comment]
Grouping is already implemented on the print view right now on master. Francesco wants sorting on the main order page. He should be submitting a pull request with the change.


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by camilleriluke** [comment]
I've been extremely busy these couple of weeks, I will try to sort these pull requests some time this week.
